"""
Relevance Agent — FinMe

Decides whether an article is worth storing in Qdrant at all.

Classifications:
    RELEVANT    — financially meaningful, store it
    IRRELEVANT  — noise, skip entirely

Examples of IRRELEVANT:
    - Stock price ticker updates ("ITC Share Price Live Updates")
    - Generic listicles with no analysis ("10 stocks above 200 DMA")
    - Celebrity / sports / entertainment news
    - IPO GMP-only articles with no analysis
    - Duplicate price movement reports with no context

Examples of RELEVANT:
    - Earnings reports and analyst reactions
    - M&A, acquisitions, partnerships
    - Macro events (RBI policy, Fed decisions, inflation data)
    - Geopolitical events with market impact
    - Sector-level analysis and trends
    - Company-specific fundamental news
"""

import os
import json
import logging
import requests
from enum import Enum

logger = logging.getLogger(__name__)

OLLAMA_URL   = os.getenv("OLLAMA_URL", "http://localhost:11434") + "/api/chat"
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "mistral:latest")
OLLAMA_TIMEOUT = 30


class RelevanceDecision(str, Enum):
    RELEVANT   = "RELEVANT"
    IRRELEVANT = "IRRELEVANT"


# ──────────────────────────────────────────────
# Noise patterns — fast pre-filter before LLM
# ──────────────────────────────────────────────

NOISE_TITLE_PATTERNS = [
    "share price live",
    "stock price live",
    "live updates",
    "live blog",
    "price today live",
    "current price shows",
    "experiences a decline in returns",   # ET autogenerated ticker titles
    "reports a substantial drop in",
    "check gmp",                          # IPO GMP-only articles
    "gmp today",
    "subscription status",
]

NOISE_DOMAINS = [
    "liveblog",
    "livestock",   # ET URL pattern for live stock blogs
]


def is_obvious_noise(article: dict) -> bool:
    """
    Fast heuristic check before calling LLM.
    Returns True if article is obviously irrelevant.
    """
    title = article.get("title", "").lower()
    url   = article.get("link", "").lower()

    if any(p in title for p in NOISE_TITLE_PATTERNS):
        return True
    if any(p in url for p in NOISE_DOMAINS):
        return True

    return False


# ──────────────────────────────────────────────
# Public entry point
# ──────────────────────────────────────────────

def classify_relevance(article: dict) -> dict:
    """
    Decide if an article is worth storing in Qdrant.

    Args:
        article: RSS article dict with title, summary, link

    Returns:
        {
            "decision": "RELEVANT" | "IRRELEVANT",
            "reason":   "...",
            "method":   "pattern" | "heuristic" | "llm"
        }
    """

    # Fast path — obvious noise patterns
    if is_obvious_noise(article):
        return _result(
            RelevanceDecision.IRRELEVANT,
            "Matched noise pattern (ticker/liveblog/GMP).",
            "pattern",
        )

    # Check title length — very short titles are usually auto-generated tickers
    title = article.get("title", "")
    summary = article.get("summary", "")

    if len(title) < 20:
        return _result(
            RelevanceDecision.IRRELEVANT,
            "Title too short — likely auto-generated ticker.",
            "heuristic",
        )

    # If no summary available, use heuristic keyword check
    if not summary.strip():
        return _heuristic_relevance(article)

    # LLM classification for borderline cases
    llm_result = _classify_with_llm(article)
    if llm_result:
        return llm_result

    # LLM unavailable — fall back to heuristics
    return _heuristic_relevance(article)


# ──────────────────────────────────────────────
# LLM classification
# ──────────────────────────────────────────────

def _classify_with_llm(article: dict) -> dict | None:
    """
    Calls Ollama to classify article relevance.
    Returns decision dict or None if call fails.
    """
    title   = article.get("title", "")
    summary = article.get("summary", "")[:400]

    prompt = f"""You are a financial news relevance classifier for a market intelligence system.

Classify the article as RELEVANT or IRRELEVANT.

RELEVANT articles contain:
- Earnings, revenue, profit/loss reports
- M&A, acquisitions, mergers, partnerships, JVs
- Central bank decisions (RBI, Fed, ECB)
- Economic data (GDP, inflation, employment, trade)
- Geopolitical events with direct market impact
- Regulatory changes affecting companies or sectors
- IPO analysis (not just GMP/subscription status)
- Analyst upgrades/downgrades with reasoning
- Company-specific fundamental news
- Sector trends with data or analysis

IRRELEVANT articles are:
- Live price ticker updates
- "Stocks to watch" listicles with no analysis
- Pure GMP/subscription status articles
- Sports, entertainment, celebrity news
- Generic "market closes up/down X%" with no context
- Repeated price movement updates with no new information

Article:
Title: {title}
Summary: {summary}

Respond with ONLY this JSON (no markdown, no explanation):
{{"decision": "RELEVANT", "reason": "one sentence"}}"""

    try:
        logger.debug("🤖 [relevance LLM] Classifying: %s", title[:60])

        response = requests.post(
            OLLAMA_URL,
            json={
                "model":   OLLAMA_MODEL,
                "messages": [{"role": "user", "content": prompt}],
                "stream":  False,
                "options": {"temperature": 0.0},
            },
            timeout=OLLAMA_TIMEOUT,
        )
        response.raise_for_status()
        resp_data = response.json()

        raw = resp_data.get("message", {}).get("content", "").strip()

        if not raw or resp_data.get("done_reason") == "load":
            logger.warning("⚠️  [relevance LLM] Empty response — falling back to heuristic")
            return None

        # Strip markdown fences
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed   = json.loads(raw)
        decision = parsed.get("decision", "").upper()

        if decision not in RelevanceDecision._value2member_map_:
            logger.warning("⚠️  [relevance LLM] Unknown decision '%s' — falling back", decision)
            return None

        emoji = "✅" if decision == "RELEVANT" else "🚫"
        logger.debug("%s [relevance LLM] %s — %s", emoji, decision, parsed.get("reason", ""))

        return _result(RelevanceDecision(decision), parsed.get("reason", ""), "llm")

    except requests.exceptions.ConnectionError:
        logger.warning("⚠️  [relevance LLM] Ollama not reachable — using heuristic fallback")
        return None
    except (json.JSONDecodeError, KeyError) as e:
        logger.warning("⚠️  [relevance LLM] Parse error: %s — using heuristic fallback", e)
        return None
    except Exception as e:
        logger.warning("⚠️  [relevance LLM] Call failed: %s — using heuristic fallback", e)
        return None


# ──────────────────────────────────────────────
# Heuristic fallback
# ──────────────────────────────────────────────

RELEVANT_KEYWORDS = [
    # Corporate events
    "earnings", "revenue", "profit", "loss", "ebitda", "margin",
    "acquisition", "merger", "buyback", "dividend", "ipo",
    "quarterly", "results", "guidance", "forecast",
    # Macro
    "rbi", "fed", "rate", "inflation", "gdp", "cpi", "wpi",
    "monetary policy", "repo rate", "interest rate",
    # Market events
    "rally", "selloff", "correction", "breakout", "52-week",
    "analyst", "upgrade", "downgrade", "target price",
    # Sectors
    "banking", "pharma", "it sector", "fmcg", "auto", "realty",
    "oil", "crude", "metal", "nifty", "sensex", "bse", "nse",
]

IRRELEVANT_KEYWORDS = [
    "gmp", "grey market", "subscription status", "allotment",
    "celebrity", "bollywood", "cricket", "ipl", "sports",
    "recipe", "travel", "fashion", "lifestyle",
]


def _heuristic_relevance(article: dict) -> dict:
    """Keyword-based relevance check when LLM is unavailable."""
    text = (
        article.get("title", "") + " " + article.get("summary", "")
    ).lower()

    irrelevant_hits = [kw for kw in IRRELEVANT_KEYWORDS if kw in text]
    if irrelevant_hits:
        return _result(
            RelevanceDecision.IRRELEVANT,
            f"Matched irrelevant keywords: {', '.join(irrelevant_hits[:3])}.",
            "heuristic",
        )

    relevant_hits = [kw for kw in RELEVANT_KEYWORDS if kw in text]
    if relevant_hits:
        return _result(
            RelevanceDecision.RELEVANT,
            f"Matched financial keywords: {', '.join(relevant_hits[:3])}.",
            "heuristic",
        )

    # Default to relevant if no strong signal either way
    # Better to store borderline articles than miss important ones
    return _result(
        RelevanceDecision.RELEVANT,
        "No strong signal — defaulting to relevant.",
        "heuristic",
    )


# ──────────────────────────────────────────────
# Helper
# ──────────────────────────────────────────────

def _result(decision: RelevanceDecision, reason: str, method: str) -> dict:
    return {
        "decision": decision.value,
        "reason":   reason,
        "method":   method,
    }
